FROM ubuntu:trusty
MAINTAINER dante-signal31 (dante.signal31@gmail.com)
RUN set -e
RUN apt-get update
RUN apt-get install ruby-dev build-essential git python-virtualenv curl libssl-dev libsqlite3-dev libgdbm-dev libreadline-dev libbz2-dev libncurses5-dev tk-dev python3 python3-pip -y
RUN gem install fpm